// @ts-check
// Only the icons the UI uses are bundled: esbuild tree-shakes these named imports, so registering
// an icon here is all the build needs. Every <i data-lucide> placeholder is replaced with an inline
// SVG that lucide marks aria-hidden="true" (controls carry their own aria-label).
import {
  createIcons,
  Activity,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BookOpen,
  Braces,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ClipboardList,
  Cloud,
  Cpu,
  Database,
  File,
  FileText,
  FolderOpen,
  Gauge,
  GitFork,
  HardDrive,
  Info,
  Languages,
  Laptop,
  Layers,
  Library,
  Lightbulb,
  Loader2,
  Lock,
  Menu,
  MessageSquare,
  Mic,
  MousePointerClick,
  Network,
  Paperclip,
  Plus,
  PlusCircle,
  Quote,
  RefreshCw,
  Search,
  Server,
  Settings2,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Square,
  Tablet,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  X,
  Zap,
} from 'lucide';

const ICONS = {
  Activity,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BookOpen,
  Braces,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ClipboardList,
  Cloud,
  Cpu,
  Database,
  File,
  FileText,
  FolderOpen,
  Gauge,
  GitFork,
  HardDrive,
  Info,
  Languages,
  Laptop,
  Layers,
  Library,
  Lightbulb,
  Loader2,
  Lock,
  Menu,
  MessageSquare,
  Mic,
  MousePointerClick,
  Network,
  Paperclip,
  Plus,
  PlusCircle,
  Quote,
  RefreshCw,
  Search,
  Server,
  Settings2,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Square,
  Tablet,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  X,
  Zap,
};

/**
 * Renders `<i data-lucide="…">` placeholders inside `root` (default: whole document).
 * @param {Element | Document} [root]
 */
export function refreshIcons(root = document) {
  createIcons({ icons: ICONS, root });
}
